-- 1.用户表
CREATE TABLE 'A_USERS' (
'USERID'  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
'USERNAME'  TEXT(50), --用户名
'PASSWORD'  TEXT(50), --密码
'ENABLED'  INTEGER,  --是否启用,有效1,无效0
'CREDENTIALSNONEXPIRED'  INTEGER,
'ACCOUNTNONEXPIRED'  INTEGER,  --是否过期, 有效1,无效0
'ACCOUNTNONLOCKED'  INTEGER  --是否被锁定, 有效1,无效0
);

-- 2.角色表
CREATE TABLE 'A_AUTOINCREMENT' (
'ROLEID'  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
'ROLENAME'  TEXT(50), --角色名称
'ENABLED'  INTEGER --角色是否有效,有效1,无效0
);
 
-- 3 用户_角色表
CREATE TABLE 'A_USERS_ROLES' (
'USER_ROLE_ID'  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
'USERID'  INTEGER,
'ROLEID'  INTEGER,
CONSTRAINT 'FK_UR_U' FOREIGN KEY ('USERID') REFERENCES 'A_USERS' ('USERID'),
CONSTRAINT 'FK_UR_R' FOREIGN KEY ('ROLEID') REFERENCES 'A_ROLES' ('ROLESID')
);
 
--  4.资源表resources
CREATE TABLE 'A_RESOURCES' (
'RECOURCEID'  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
'RECOURCENAME' TEXT(50)
'URL'  TEXT(255)
);
 
-- 5.角色_资源表roles_resources
CREATE TABLE 'A_ROLES_RESOURCES' (
'ROLE_RESOURCE_SID'  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
'ROLEID'  INTEGER,
'RESOURCEID'  INTEGER,
FOREIGN KEY ('ROLEID') REFERENCES 'A_ROLES' ('ROLEID'),
FOREIGN KEY ('RESOURCEID') REFERENCES 'A_RESOURCES' ('RECOURCEID')
);